version: '3.4'
services:
  super-app-db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  super-app-node:
    build: ./node
    ports:
      - "3000:3000"
